#include <stdint.h>

/***********************************************************************
 * SRAM Memory Configuration
 *
 * Defines the start address, size and end address of the SRAM
 * available on the STM32F103CBT6.
 *
 * The initial Main Stack Pointer (MSP) is placed at the end of SRAM
 * because the ARM Cortex-M3 stack grows downward.
 ***********************************************************************/

#define sram_start     0x20000000u
#define sram_size      (20u * 1024)
#define sram_end       (sram_start + sram_size)
#define stack_start    sram_end


/***********************************************************************
 * Linker Symbols
 *
 * These symbols are generated by the linker script and are used
 * by the Reset Handler during system startup.
 *
 * They define the boundaries of the .text, .data and .bss sections.
 ***********************************************************************/

extern uint32_t _etext;
extern uint32_t _sdata;
extern uint32_t _edata;
extern uint32_t _sbss;
extern uint32_t _ebss;


/***********************************************************************
 * Function Prototypes:
 * main()
 * Entry point of the user application.
 * Reset_handler()
 * Executed immediately after a processor reset.
 ***********************************************************************/

int main(void);

void Reset_handler(void);


/***********************************************************************
 * Exception and Interrupt Handlers
 *
 * Every interrupt is declared as a weak symbol and redirected to
 * default_handler().
 *
 * This allows the application to override only the handlers it
 * actually needs without modifying the startup file.
 ***********************************************************************/

void NMI_handler(void)                 __attribute__((weak, alias("default_handler")));
void HardFault_handler(void)           __attribute__((weak, alias("default_handler")));
void MemManage_handler(void)           __attribute__((weak, alias("default_handler")));
void BusFault_handler(void)            __attribute__((weak, alias("default_handler")));
void UsageFault_handler(void)          __attribute__((weak, alias("default_handler")));

void SVCall_handler(void)              __attribute__((weak, alias("default_handler")));
void Debug_Monitor_handler(void)       __attribute__((weak, alias("default_handler")));
void PendSV_handler(void)              __attribute__((weak, alias("default_handler")));
void SysTick_handler(void)             __attribute__((weak, alias("default_handler")));

void WWDG_handler(void)                __attribute__((weak, alias("default_handler")));
void PVD_handler(void)                 __attribute__((weak, alias("default_handler")));
void TAMPER_handler(void)              __attribute__((weak, alias("default_handler")));
void RTC_handler(void)                 __attribute__((weak, alias("default_handler")));
void FLASH_handler(void)               __attribute__((weak, alias("default_handler")));
void RCC_handler(void)                 __attribute__((weak, alias("default_handler")));

void EXTI0_handler(void)               __attribute__((weak, alias("default_handler")));
void EXTI1_handler(void)               __attribute__((weak, alias("default_handler")));
void EXTI2_handler(void)               __attribute__((weak, alias("default_handler")));
void EXTI3_handler(void)               __attribute__((weak, alias("default_handler")));
void EXTI4_handler(void)               __attribute__((weak, alias("default_handler")));

void DMA1_Channel1_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA1_Channel2_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA1_Channel3_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA1_Channel4_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA1_Channel5_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA1_Channel6_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA1_Channel7_handler(void)       __attribute__((weak, alias("default_handler")));

void ADC1_2_handler(void)              __attribute__((weak, alias("default_handler")));

void CAN1_TX_handler(void)             __attribute__((weak, alias("default_handler")));
void CAN1_RX0_handler(void)            __attribute__((weak, alias("default_handler")));
void CAN1_RX1_handler(void)            __attribute__((weak, alias("default_handler")));
void CAN1_SCE_handler(void)            __attribute__((weak, alias("default_handler")));

void EXTI9_5_handler(void)             __attribute__((weak, alias("default_handler")));

void TIM1_BRK_handler(void)            __attribute__((weak, alias("default_handler")));
void TIM1_UP_handler(void)             __attribute__((weak, alias("default_handler")));
void TIM1_TRG_COM_handler(void)        __attribute__((weak, alias("default_handler")));
void TIM1_CC_handler(void)             __attribute__((weak, alias("default_handler")));

void TIM2_handler(void)                __attribute__((weak, alias("default_handler")));
void TIM3_handler(void)                __attribute__((weak, alias("default_handler")));
void TIM4_handler(void)                __attribute__((weak, alias("default_handler")));

void I2C1_EV_handler(void)             __attribute__((weak, alias("default_handler")));
void I2C1_ER_handler(void)             __attribute__((weak, alias("default_handler")));
void I2C2_EV_handler(void)             __attribute__((weak, alias("default_handler")));
void I2C2_ER_handler(void)             __attribute__((weak, alias("default_handler")));

void SPI1_handler(void)                __attribute__((weak, alias("default_handler")));
void SPI2_handler(void)                __attribute__((weak, alias("default_handler")));

void USART1_handler(void)              __attribute__((weak, alias("default_handler")));
void USART2_handler(void)              __attribute__((weak, alias("default_handler")));
void USART3_handler(void)              __attribute__((weak, alias("default_handler")));

void EXTI15_10_handler(void)           __attribute__((weak, alias("default_handler")));

void RTCAlarm_handler(void)            __attribute__((weak, alias("default_handler")));
void OTG_FS_WKUP_handler(void)         __attribute__((weak, alias("default_handler")));

void TIM5_handler(void)                __attribute__((weak, alias("default_handler")));
void SPI3_handler(void)                __attribute__((weak, alias("default_handler")));

void UART4_handler(void)               __attribute__((weak, alias("default_handler")));
void UART5_handler(void)               __attribute__((weak, alias("default_handler")));

void TIM6_handler(void)                __attribute__((weak, alias("default_handler")));
void TIM7_handler(void)                __attribute__((weak, alias("default_handler")));

void DMA2_Channel1_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA2_Channel2_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA2_Channel3_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA2_Channel4_handler(void)       __attribute__((weak, alias("default_handler")));
void DMA2_Channel5_handler(void)       __attribute__((weak, alias("default_handler")));

void ETH_handler(void)                 __attribute__((weak, alias("default_handler")));
void ETH_WKUP_handler(void)            __attribute__((weak, alias("default_handler")));

void CAN2_TX_handler(void)             __attribute__((weak, alias("default_handler")));
void CAN2_RX0_handler(void)            __attribute__((weak, alias("default_handler")));
void CAN2_RX1_handler(void)            __attribute__((weak, alias("default_handler")));
void CAN2_SCE_handler(void)            __attribute__((weak, alias("default_handler")));

void OTG_FS_handler(void)              __attribute__((weak, alias("default_handler")));
/***********************************************************************
 * Interrupt Vector Table
 *
 * The vector table is placed in the ".isr_vector" section so that
 * the linker locates it at the beginning of Flash memory.
 *
 * During reset, the Cortex-M3 processor automatically:
 *   1. Loads the initial Main Stack Pointer (MSP) from the first entry.
 *   2. Loads the Reset Handler address from the second entry.
 *   3. Uses the remaining entries whenever an exception or interrupt
 *      occurs.
 ***********************************************************************/

uint32_t vector[] __attribute__((section(".isr_vector"))) =
{
	/*******************************************************************
	 * Initial Stack Pointer
	 *
	 * The first entry of the vector table contains the initial value
	 * of the Main Stack Pointer (MSP).
	 *******************************************************************/
	stack_start,

	/*******************************************************************
	 * Cortex-M3 Core Exception Handlers
	 *******************************************************************/
	(uint32_t)&Reset_handler,
	(uint32_t)&NMI_handler,
	(uint32_t)&HardFault_handler,
	(uint32_t)&MemManage_handler,
	(uint32_t)&BusFault_handler,
	(uint32_t)&UsageFault_handler,

	/* Reserved */
	0,
	0,
	0,
	0,

	(uint32_t)&SVCall_handler,
	(uint32_t)&Debug_Monitor_handler,

	/* Reserved */
	0,

	(uint32_t)&PendSV_handler,
	(uint32_t)&SysTick_handler,

	/*******************************************************************
	 * Peripheral Interrupt Handlers
	 *******************************************************************/
	(uint32_t)&WWDG_handler,
	(uint32_t)&PVD_handler,
	(uint32_t)&TAMPER_handler,
	(uint32_t)&RTC_handler,
	(uint32_t)&FLASH_handler,
	(uint32_t)&RCC_handler,

	(uint32_t)&EXTI0_handler,
	(uint32_t)&EXTI1_handler,
	(uint32_t)&EXTI2_handler,
	(uint32_t)&EXTI3_handler,
	(uint32_t)&EXTI4_handler,

	(uint32_t)&DMA1_Channel1_handler,
	(uint32_t)&DMA1_Channel2_handler,
	(uint32_t)&DMA1_Channel3_handler,
	(uint32_t)&DMA1_Channel4_handler,
	(uint32_t)&DMA1_Channel5_handler,
	(uint32_t)&DMA1_Channel6_handler,
	(uint32_t)&DMA1_Channel7_handler,

	(uint32_t)&ADC1_2_handler,

	(uint32_t)&CAN1_TX_handler,
	(uint32_t)&CAN1_RX0_handler,
	(uint32_t)&CAN1_RX1_handler,
	(uint32_t)&CAN1_SCE_handler,

	(uint32_t)&EXTI9_5_handler,

	(uint32_t)&TIM1_BRK_handler,
	(uint32_t)&TIM1_UP_handler,
	(uint32_t)&TIM1_TRG_COM_handler,
	(uint32_t)&TIM1_CC_handler,

	(uint32_t)&TIM2_handler,
	(uint32_t)&TIM3_handler,
	(uint32_t)&TIM4_handler,

	(uint32_t)&I2C1_EV_handler,
	(uint32_t)&I2C1_ER_handler,

	(uint32_t)&I2C2_EV_handler,
	(uint32_t)&I2C2_ER_handler,

	(uint32_t)&SPI1_handler,
	(uint32_t)&SPI2_handler,

	(uint32_t)&USART1_handler,
	(uint32_t)&USART2_handler,
	(uint32_t)&USART3_handler,

	(uint32_t)&EXTI15_10_handler,

	(uint32_t)&RTCAlarm_handler,
	(uint32_t)&OTG_FS_WKUP_handler,

	/*******************************************************************
	 * Reserved Interrupt Vectors
	 *
	 * These interrupt positions are reserved by the ARM architecture
	 * or are not implemented on the STM32F103CBT6.
	 *******************************************************************/
	0,
	0,
	0,
	0,
	0,
	0,
	0,

	(uint32_t)&TIM5_handler,
	(uint32_t)&SPI3_handler,
	(uint32_t)&UART4_handler,
	(uint32_t)&UART5_handler,

	(uint32_t)&TIM6_handler,
	(uint32_t)&TIM7_handler,

	(uint32_t)&DMA2_Channel1_handler,
	(uint32_t)&DMA2_Channel2_handler,
	(uint32_t)&DMA2_Channel3_handler,
	(uint32_t)&DMA2_Channel4_handler,
	(uint32_t)&DMA2_Channel5_handler,

	(uint32_t)&ETH_handler,
	(uint32_t)&ETH_WKUP_handler,

	(uint32_t)&CAN2_TX_handler,
	(uint32_t)&CAN2_RX0_handler,
	(uint32_t)&CAN2_RX1_handler,
	(uint32_t)&CAN2_SCE_handler,

	(uint32_t)&OTG_FS_handler
};
/************************************************************************
 * Reset Handler
 *
 * This function is executed immediately after a processor reset.
 *
 * It performs the required runtime initialization before transferring
 * control to the user application.
 *
 * The initialization sequence is:
 *
 * 1. Copy the initialized .data section from Flash to SRAM.
 * 2. Clear the .bss section by filling it with zeros.
 * 3. Initialize the C runtime library.
 * 4. Call the application's main() function.
 ***********************************************************************/
void Reset_handler(void)
{
	/********************************************************************
	 * Copy the .data Section
	 *
	 * The initial values of global and static variables are stored in
	 * Flash memory by the linker.
	 *
	 * During startup, these values are copied into SRAM so they can be
	 * modified while the program is running.
	 ********************************************************************/

	uint32_t size = (uint32_t)&_edata - (uint32_t)&_sdata;

	/* Destination Address : SRAM */
	uint8_t *dtp = (uint8_t *)&_sdata;

	/* Source Address : Flash */
	uint8_t *srp = (uint8_t *)&_etext;

	for(uint32_t i = 0; i < size; i++)
	{
		*dtp++ = *srp++;
	}


	/********************************************************************
	 * Initialize the .bss Section
	 *
	 * Global and static variables without an initial value are placed
	 * in the .bss section.
	 *
	 * According to the C standard, these variables must contain zero
	 * before main() begins execution.
	 ********************************************************************/

	size = (uint32_t)&_ebss - (uint32_t)&_sbss;

	dtp = (uint8_t *)&_sbss;

	for(uint32_t i = 0; i < size; i++)
	{
		*dtp++ = 0;
	}
	/********************************************************************
	 * Transfer Control to the Application
	 *
	 * After completing all runtime initialization, execution is
	 * transferred to the user application's entry point.
	 ********************************************************************/

	main();
}
/************************************************************************
 * Default Handler
 *
 * All interrupt handlers are declared as weak symbols and are
 * aliased to this function.
 *
 * If an interrupt occurs for which the application has not provided
 * a custom handler, the processor branches to this function instead.
 *
 * Entering an infinite loop prevents the processor from executing
 * unintended instructions and makes unexpected interrupts easier
 * to identify during debugging.
 ***********************************************************************/
void default_handler(void)
{
	while(1)
	{
		/* Stay here until the system is reset or a debugger is attached. */
	}
}